### ISSUE TITLE
V2 feature list

### ISSUE THREAD

**Issue by AlexGhiondea** [AlexGhiondea/CommandLine#46]
- [x] Support .NET Standard 2.0 #43 
- [x] Ensure that TryParse never throws an exception #40 
- [x] Ensure that Parse always throws the exception #40 
- [x] Add support for retrieving values for the optional arguments from the environment
- [x] Ensure that the parser is configurable
  - [x] Add support for not logging to the console in case of error
  - [x] Add support for specifying the prefix for env-vars
- [ ] ~Support for parameter validation / configuration #44~
